### ISSUE TITLE
Roblox documentation

### ISSUE THREAD

**Issue by wepfen** [michrblx/bladeball#2]
Hello !

I got some questions:

- where do you document yourself to script in roblox and also know the variables that blade ball use in the game (maybe you just do some reverse engineering).

- Also, how do you interact with the game using your script.

Thanks in advance !

**Comment by myqhael** [comment]
dex explorer for your first question and script executors for your second question..

**Comment by wepfen** [comment]
Thank you very much.

Also which script executor do you use.

**Comment by myqhael** [comment]
> Thank you very much.
> 
> Also which script executor do you use.

none because roblox added a new anticheat if you didnt know..

**Comment by wepfen** [comment]
Nooooooo
